### ISSUE TITLE
At RPi 3 rpitx randomly shifting frequency during TX

### ISSUE THREAD

**Issue by ha7dcd** [F5OEO/rpitx#21] opened 2016-04-22 11:29 UTC
I've experienced a strange shifting of 2.8 MHz upwards from the carrier. Randomly the nominal 14MHz transmission is just shifted up to 16.8 MHz... then back.

 Using latest Raspbian Jessie (as of today 22/04/2016), all the update, upgrade, disti upgrade done before. Cloned and installed riptx just right now from github.

![strong_spurious_14mhz_rpi3_gpio18](https://cloud.githubusercontent.com/assets/15707934/14740282/0c010f06-088e-11e6-803e-d064ad116aac.png)
![strong_spurious_14mhz_rpi3_-c 1_switch](https://cloud.githubusercontent.com/assets/15707934/14740285/11e0266e-088e-11e6-9a1b-07e57350731a.png)

**Comment by freebil** [comment] 2016-04-22 11:33
Hello! How did you see these diagrams? Thanks.

**Comment by ha7dcd** [comment] 2016-04-22 11:54
Using this: https://signalhound.com/products/usb-sa44b/
However you can catch the signals also with RTL-SDR or SDRPlay(better) too..

**Comment by freebil** [comment] 2016-04-22 12:13
Ok, thank you!

**Comment by tomswartz07** [comment] 2016-04-22 13:40
Perhaps I'm reading the graphic incorrectly, but both images show Mkr1 and Mkr2 having the same frequency.

It appears that the only difference between the two images is the center frequency.
Image 1 has a center freq of 25MHz and Image 2 has a center freq of 14MHz.

Am I correct in reading this?

**Comment by ha7dcd** [comment] 2016-04-22 13:59
No, you are mistaken the fact that the Mkr1 is the intended transmission (14 MHz) Mkr2 showing the randomly shifter carrier (16.8 MHz)

The reason for two screenshot is the different span

**Comment by ha7dcd** [comment] 2016-04-22 14:03
Maybe this video gives a better understanding of this phenomena:
[https://www.dropbox.com/s/xxihgxrakkejlji/14MHz_and_random_16M8_shifting_RPi3_gpio18.png.MP4?dl=0](url)

**Comment by ha7dcd** [comment] 2016-04-24 18:16
My friend András, @ha7ilm noticed that this shift issue possibly caused by the dynamic CPU frequency change algorithm in RPi 3. I've tested it and looks like a workaround for the problem:
" sudo -s
echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor "

![rpitx_rpi3_freq_shifting_issue_solved](https://cloud.githubusercontent.com/assets/15707934/14769474/3b3e507c-0a59-11e6-846a-8b1225c91617.png)

**Comment by ha7ilm** [comment] 2016-04-24 20:06
It seems like this is caused by the `cpufreq` kernel module, which changes the frequency in order to save power. The `ondemand`governor is enabled by default.

**Comment by F5OEO** [comment] 2016-07-01 18:17
force_turbo=1 in /boot/config.txt shoud solve the issue

**Comment by jnk0le** [comment] 2016-07-01 22:54
The problem is frequency of PLLC (used by rpitx), which drifts with overclock.

**Comment by F5OEO** [comment] 2016-08-27 13:41
Should be fixed with https://github.com/F5OEO/rpitx/commit/feb6f4cf3e62f013688671abd5d365b6753baf1e : PLL_D is used which is very stable compare to PLL_C (variable)

**Closed** 2018-11-23 22:31 UTC
Labels: V1 related (not maintained)
